version: '3.0'
services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  server: 
    image: doyoumind
    ports:
      - 8000:8000
    volumes: 
      - snaps_data:/snaps
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.server run-server -h '0.0.0.0' -db 'mongodb://mongodb:27017' "rabbitmq://rabbitmq:5672/"
    depends_on: 
      - rabbitmq
      - mongodb
  parse_pose:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.parsers run-parser 'pose' 'rabbitmq://rabbitmq:5672/'
    depends_on: 
      - rabbitmq
  parse_feelings:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.parsers run-parser 'feelings' 'rabbitmq://rabbitmq:5672/'
    depends_on: 
      - rabbitmq
  parse_color_image:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.parsers run-parser 'color_image' 'rabbitmq://rabbitmq:5672/'
    depends_on: 
      - rabbitmq
  parse_depth_image:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.parsers run-parser 'depth_image' 'rabbitmq://rabbitmq:5672/'
    depends_on: 
      - rabbitmq
  saver:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.saver run-saver 'mongodb://mongodb:27017' 'rabbitmq://rabbitmq:5672/'
    depends_on: 
      - rabbitmq
      - mongodb
  
  api:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    ports:
      - 5000:5000
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.api run-server -h '0.0.0.0' -d 'mongodb://mongodb:27017'
    depends_on: 
      - rabbitmq

  gui:
    image: doyoumind
    volumes: 
      - snaps_data:/snaps
    ports:
      - 8080:8080
    command: ./wait_for_it.sh rabbitmq:5672 -- python3.8 -m doyoumind.gui run-server -h '0.0.0.0' -H '0.0.0.0'
    depends_on: 
      - rabbitmq


volumes:
  snaps_data: 

 